'use strict'
const { app, BrowserWindow, ipcMain, session } = require('electron')
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict')
const source = process.env.AKD_TEST_ASAR ? path.join(process.env.AKD_TEST_ASAR, 'src') : path.join(__dirname, '../src')
const N = require(path.join(source, 'network-settings'))
const { registerNetworkSettings } = require(path.join(source, 'network-settings-ipc'))
const { createSessionBinding } = require(path.join(source, 'session-binding'))
const { createSubscriptionSync } = require(path.join(source, 'subscription-profiles'))
const i18n = require(path.join(source, 'i18n'))
const snapshot = require(path.join(source, 'subscription-models.json'))
const evidence = path.join(__dirname, '../../dist/ux-fix-runtime/evidence' + (process.env.AKD_TEST_ASAR ? '-packaged' : ''))
fs.mkdirSync(evidence, { recursive: true })
const userData = fs.mkdtempSync(path.join(evidence, 'userData-'))
app.setPath('userData', userData); app.on('window-all-closed', () => {})
setTimeout(() => app.exit(3), 55000).unref()
const checks = [], errors = []
const check = (name, ok) => { checks.push({ name, ok: !!ok }); console.log((ok ? 'PASS ' : 'FAIL ') + name); assert.ok(ok, name) }
const markdown = '# 调教建议\n\n**粗体** 与 *强调*，`pitchDelta`。\n\n1. 音高\n2. 气声\n   - 自然过渡\n\n> 不改旧轨道\n\n| 参数 | 数值 |\n|---|---|\n| 气声 | 0.2 |\n\n```js\nconst value = "<safe>";\n```\n\n- [x] 完成检查\n- [ ] 等待试听\n\n[说明](https://example.com/)'

app.whenReady().then(async () => {
  i18n.init({ getPath: () => userData, getSystemLocale: () => 'zh-CN' })
  const orb = new BrowserWindow({ width: 740, height: 880, show: false, webPreferences: { preload: path.join(source, 'orb-preload.js'), contextIsolation: true, nodeIntegration: false } })
  const settings = new BrowserWindow({ width: 900, height: 900, show: false, webPreferences: { preload: path.join(__dirname, 'test-settings-preload.cjs'), contextIsolation: true, nodeIntegration: false, additionalArguments: ['--akd-test-ux'] } })
  for (const win of [orb, settings]) win.webContents.on('console-message', (_e, level, message) => { if (level >= 3 && !message.includes('Electron Security Warning')) errors.push(message) })
  ipcMain.on('akdagent-i18n-sync', (event) => { event.returnValue = { locale: i18n.getLocale(), dict: i18n.dictFor(event.sender === orb.webContents ? 'orb' : 'settings') } })
  ipcMain.on('akdagent-open-external', () => {})
  let currentSession = null, selection = null, creates = 0, reveals = 0, modelPrompts = 0, failSelection = false, catalogReads = 0
  let modelSettings = {}, authState = { flows: { ok: true, at: new Date().toISOString(), flows: [{ key: 'llm-pi-ai/openai-codex', label: 'OpenAI Codex', methods: [{ id: 'oauth', label: 'ChatGPT' }] }] }, attempt: { ok: true, state: 'idle' } }
  const binder = createSessionBinding({ ready: async () => {}, segmentKey: () => 'test-project', ensure: async () => { if (!currentSession) { creates++; currentSession = 'test-session'; orb.webContents.send('akdagent-session-bound', { sessionId: currentSession }) } return currentSession }, show: () => { reveals++; orb.webContents.send('akdagent-open-orb-panel') } })
  const sync = createSubscriptionSync({ readState: () => authState, readSettings: () => modelSettings,
    saveSettings: (next) => { modelSettings = next; return true }, remember: () => {}, notify: (result) => {
      for (const win of [orb, settings]) win.webContents.send('akdagent-model-catalog-changed', result)
    } })
  const catalog = () => ({ ok: true, default: { provider: 'deepseek-official', model: 'deepseek-flash' }, groups: [{ id: 'deepseek-official', name: 'DeepSeek', models: [{ id: 'deepseek-flash', name: 'DeepSeek' }] }, ...(modelSettings['llm-pi-ai']?.providers?.['openai-codex'] ? [{ id: 'openai-codex', name: 'OpenAI Codex', models: [{ id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna' }, ...snapshot.routes['openai-codex']] }] : [])] })
  ipcMain.handle('akdagent-model-catalog', () => { catalogReads++; return catalog() })
  ipcMain.handle('akdagent-session-model', () => ({ ok: true, next: selection, lastUsed: null, fallback: !currentSession }))
  ipcMain.handle('akdagent-select-session-model', async (_e, id, provider, model) => {
    await binder.bind({ reveal: true }); if (failSelection) return { ok: false, error: 'test backend unavailable' }
    selection = { provider, model }; for (const win of [orb, settings]) win.webContents.send('akdagent-session-model', selection)
    return { ok: true, selected: selection, sessionId: currentSession }
  })
  ipcMain.handle('akdagent-auth-flows', async () => ({ ...authState, subscription: await sync.sync() }))
  ipcMain.handle('akdagent-get-providers', () => ({ providers: Object.entries(modelSettings['llm-pi-ai']?.providers || {}).map(([id, profile]) => ({ id, displayName: profile.displayName, kind: 'pi-ai', namespace: 'llm-pi-ai', subscription: true, models: [], apiKeyEnv: '', defaultModel: '', hasKey: false })), presets: [], credentialKeys: [], credentialSource: 'isolated', credentialReadable: true }))
  ipcMain.handle('akdagent-agent-ready-query', () => ({ ready: true }))
  ipcMain.handle('akdagent-stt-status', () => null)
  ipcMain.handle('akdagent-agent-history', () => ({ ok: true, events: [{ type: 'assistant/message', data: { message: { content: [{ type: 'text', text: markdown }] } } }] }))
  ipcMain.handle('akdagent-agent-session-state', () => ({ ok: true }))
  ipcMain.handle('akdagent-agent-send', () => { modelPrompts++; return { ok: false, error: 'prompts prohibited in tests' } })
  const store = N.createStore(userData), active = N.resolvePolicy(N.schema.defaults(), {})
  registerNetworkSettings({ ipcMain, session, store, inherited: {}, getActive: () => active, getSender: () => settings.webContents, resolveNodeBin: () => process.env.AKD_TEST_NODE, checkIdle: async () => {}, askRestart: async () => false, restart: () => {} })
  await orb.loadFile(path.join(source, 'orb.html')); await settings.loadFile(path.join(source, 'settings.html'))
  const js = (code, win = settings) => win.webContents.executeJavaScript(code)
  const wait = (ms = 160) => new Promise((r) => setTimeout(r, ms))
  const input = (id, value) => js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))})()`)
  const click = (id) => js(`document.getElementById(${JSON.stringify(id)}).click()`)
  await js(`activatePage('network')`); await wait(); await click('network-add')
  await input('network-name', '启动默认代理'); await input('network-port', '7897')
  const pid = await js(`document.getElementById('network-profile').value`)
  await input('network-route', pid); await wait()
  check('route selection persists immediately without clicking Save', store.read().selected === pid && store.read().revision === 1)
  await js(`activatePage('model')`); await wait()
  check('selector does not pretend a model was selected before binding', await js(`document.getElementById('session-model-select').value===''`))
  const readsBefore = catalogReads
  authState.attempt = { ok: true, state: 'authorized', method: 'oauth', key: 'llm-pi-ai/openai-codex', id: 1, at: 'completed' }
  await js(`loadAuthFlows()`); await wait(350)
  check('successful subscription automatically creates exact provider without API key', !!modelSettings['llm-pi-ai']?.providers?.['openai-codex'] && !modelSettings['llm-pi-ai'].providers['openai-codex'].apiKeyEnv)
  check('both cached model dropdowns refresh after subscription success', catalogReads > readsBefore && await js(`!!document.querySelector('#session-model-select optgroup[label="OpenAI Codex"]')`) && await js(`!!document.querySelector('#model-select optgroup[label="OpenAI Codex"]')`, orb))
  check('subscription card shows OAuth status instead of a missing API key', await js(`document.getElementById('provider-list').textContent.includes('无需 API 密钥')`))
  check('new GPT-6 family appears in both model selectors', await js(`['gpt-6.1-sol','gpt-6-sol','gpt-6-luna'].every(id=>[...document.querySelectorAll('#session-model-select option')].some(o=>o.value.endsWith(id)))`) && await js(`['gpt-6.1-sol','gpt-6-sol','gpt-6-luna'].every(id=>[...document.querySelectorAll('#model-select option')].some(o=>o.value.endsWith(id)))`, orb))
  await input('session-model-select', 'openai-codex\u0000gpt-6.1-sol'); await wait()
  check('first model selection automatically shows chat and binds one session', creates === 1 && reveals === 1 && await js(`document.getElementById('chat-overlay').classList.contains('open')`, orb))
  check('historical assistant Markdown uses headings, bold, lists, table, quote and code', await js(`['h1','strong','ol','ul','table','blockquote','pre code'].every(s=>document.querySelector('.out-text '+s))`, orb))
  check('binding and opening concurrently restore history only once', await js(`document.querySelectorAll('.out-text').length===1`, orb))
  check('task checkboxes are inert and preserve checked state', await js(`document.querySelectorAll('.out-text input[type=checkbox]').length===2 && document.querySelector('.out-text input').checked && document.querySelector('.out-text input').disabled`, orb))
  failSelection = true; await input('session-model-select', 'deepseek-official\u0000deepseek-flash'); await wait()
  check('model switch failure stays inline and leaves selector retryable', await js(`document.getElementById('session-model-text').textContent.includes('切换模型失败') && !document.getElementById('session-model-select').disabled`))
  failSelection = false
  const frame = (type, data) => orb.webContents.send('akdagent-agent-event', { payload: { sessionId: currentSession, type: 'session/event', event: { type, data } } })
  frame('assistant/live-chunk', { turn: 1, stream: [{ type: 'text-delta', text: '# 实时\n\n**分' }] }); await wait()
  frame('assistant/live-chunk', { turn: 1, stream: [{ type: 'text-delta', text: '段粗体**\n\n```js\n1 < 2\n```' }] }); frame('turn/end', { reason: { kind: 'completed' } }); await wait()
  check('streamed split Markdown finalizes with bold and escaped code', await js(`(()=>{const n=[...document.querySelectorAll('.out-text')].at(-1);return n.querySelector('strong')?.textContent==='分段粗体'&&n.querySelector('pre code')?.textContent.includes('1 < 2')})()`, orb))
  frame('assistant/live-chunk', { turn: 2, stream: [{ type: 'text-delta', text: '长回复\n\n' + '继续核对自然歌唱。\n\n'.repeat(60) }] }); await wait()
  await js(`document.getElementById('chat-body').scrollTop=0`, orb)
  frame('assistant/live-chunk', { turn: 2, stream: [{ type: 'text-delta', text: '\n新增内容。' }] }); await wait()
  check('streaming respects manual scroll-up', await js(`document.getElementById('chat-body').scrollTop===0`, orb))
  frame('turn/end', { reason: { kind: 'completed' } }); await wait()
  const malicious = '<script>globalThis.pwned=1</script>\n<img src=x onerror="globalThis.pwned=2">\n\n[bad](javascript:alert(1))\n![remote](https://evil.invalid/tracker.png)\n\n[local](file:///C:/secret)'
  await js(`AKDMarkdown.render(document.querySelector('.out-text'),${JSON.stringify(malicious)})`, orb)
  check('hostile Markdown cannot execute scripts, load images, or create unsafe links', await js(`!globalThis.pwned && !document.querySelector('.out-text script,.out-text img') && ![...document.querySelectorAll('.out-text a')].some(a=>/^(javascript|file|data):/i.test(a.getAttribute('href')))`, orb))
  await js(`AKDMarkdown.render(document.querySelector('.out-text'),${JSON.stringify(markdown)})`, orb)
  for (const locale of i18n.LOCALES) {
    i18n.setLocale(locale)
    for (const [win, namespace] of [[settings, 'settings'], [orb, 'orb']]) win.webContents.send('akdagent-i18n-update', { locale, dict: i18n.dictFor(namespace) })
    await wait(); settings.setSize(620, 900); await js(`activatePage('network')`); await wait()
    check('startup selector localized and usable at 620px in ' + locale, await js(`!document.getElementById('page-network').textContent.includes('ux.') && document.getElementById('network-route').value===${JSON.stringify(pid)} && document.getElementById('main').scrollWidth<=document.getElementById('main').clientWidth`))
    fs.writeFileSync(path.join(evidence, 'network-' + locale + '.png'), (await settings.webContents.capturePage()).toPNG())
  }
  await js(`document.getElementById('chat-body').scrollTop=0`, orb)
  fs.writeFileSync(path.join(evidence, 'chat-markdown.png'), (await orb.webContents.capturePage()).toPNG())
  check('no inference or real provider calls during UI tests', modelPrompts === 0)
  check('no renderer failures and complete dictionaries', errors.length === 0 && Object.keys(i18n.audit()).length === 0 && await js(`document.querySelectorAll('[data-rej]').length===0`))
  fs.writeFileSync(path.join(evidence, 'ux-verification.json'), JSON.stringify({ checks, errors, modelPrompts, isolated: true }, null, 2))
  app.exit(0)
}).catch((error) => { console.error(error.stack); console.error(JSON.stringify(errors)); app.exit(1) })
